Sistemas de Suporte à Decisão - TPC 3

Crie um ficheiro em python para trabalhar o datase





In [0]:
datasets.california_housing

Nesse ficheiro, crie um script (função) por alínea que lhe permita gerar novos datasets a partir do dataset principal, onde tenha usado cada um dos seguintes métodos de pre-processamento:

1) Aggregation

2) Sampling

4) Dimensionality Reduction 

5) Feature Subset Selection 

6) Feature Creation 

7) Discretization and Binarization 

8) Attribute Transformation


In [0]:
import sklearn.datasets as datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from sklearn import preprocessing

In [3]:

#colocar os dados na variavel data
data = datasets.california_housing.fetch_california_housing()

#colocar os dados numa tabela
dframe = pd.DataFrame(data = data.data, columns=data.feature_names)
dframe.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

**1. AGGREGATION**

In [4]:
aggregation = dframe.loc[dframe["AveRooms"]<4,:]
aggregation.aggregate(["sum", "mean", "max"])

MedInc      HouseAge     AveRooms    AveBedrms    Population  \
sum   6865.315100  89960.000000  9914.116674  3003.755845  4.550410e+06   
mean     2.393764     31.366806     3.456805     1.047335  1.586614e+03   
max     10.226400     52.000000     3.998331     2.111111  1.127200e+04   

          AveOccup      Latitude      Longitude  
sum   10104.593373  99867.940000 -341424.340000  
mean      3.523219     34.821457    -119.046144  
max    1243.333333     40.870000    -114.650000

**2. SAMPLING**

In [5]:
dframe.sample(frac = 0.1)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
8540    3.1325      27.0  4.378086   1.055556      2141.0  3.304012     33.89   
6705    3.6997      24.0  3.991813   1.100585      4210.0  1.641326     34.14   
15507   4.3846      15.0  6.263598   1.046025       827.0  3.460251     33.14   
11664   4.0865      30.0  5.132743   0.991150      1434.0  3.172566     33.85   
18799   2.2250      26.0  5.742718   1.339806       513.0  2.490291     40.97   
4090    4.3214      18.0  5.645646   1.261261       681.0  2.045045     34.15   
9659    2.1434      42.0  6.631818   1.309091      1182.0  2.686364     41.78   
6476    3.7222      34.0  4.546135   1.139651      1485.0  3.703242     34.09   
12209   3.2440       7.0  6.220820   1.110410       964.0  3.041009     33.60   
18432   7.4323      16.0  7.837288   1.027119      1158.0  3.925424     37.26   
13796   1.6838      14.0  4.745856   1.171271       541.0  2.988950     34.58   
4285    1.8277      30.0  2.623206   1.154306      2197.0  2.627990     34.10   
10557   5.2325      16.0  6.492669   1.092375      1525.0  2.236070     33.63   
12989   2.7477       4.0  4.509517   1.210835      1195.0  1.749634     38.68   
8765    6.0150      41.0  6.794964   1.082734       802.0  2.884892     33.81   
18761   2.3287      16.0  5.705000   1.100000       563.0  2.815000     40.63   
19063   4.7356      18.0  6.815668   1.133641       550.0  2.534562     38.31   
18135   5.0785      33.0  5.681716   1.119639      1158.0  2.613995     37.35   
16019  10.7309      52.0  7.850365   1.021898       762.0  2.781022     37.73   
16352   3.5684       7.0  4.670715   1.159244      1518.0  2.048583     38.03   
6202    3.8837      32.0  5.559719   1.053864      1580.0  3.700234     34.07   
7789    4.5370      29.0  5.126126   0.977477       964.0  4.342342     33.89   
14663   3.8719      29.0  5.484674   1.022989      1392.0  2.666667     32.80   
7957    3.0893      42.0  4.686610   1.056980      1161.0  3.307692     33.88   
3501    2.6193      28.0  4.238636   1.052273      1182.0  2.686364     34.27   
11572   2.2981      26.0  3.659829   1.020513      2038.0  3.483761     33.76   
2887    1.6009      39.0  5.121839   1.245977      1516.0  3.485057     35.39   
20220   4.1250      52.0  5.639798   1.057935       941.0  2.370277     34.28   
6971    3.4312      52.0  6.359909   1.050114      1177.0  2.681093     33.99   
6035    1.9643      32.0  3.882250   1.149385      1718.0  3.019332     34.06   
...        ...       ...       ...        ...         ...       ...       ...   
8312    4.6852      52.0  5.509687   1.029806      1436.0  2.140089     33.77   
15137   4.1050      16.0  6.035963   1.041763      2515.0  2.917633     32.83   
8710    5.6426      35.0  6.745946   1.113514       551.0  2.978378     33.85   
3029    2.9952      44.0  5.534296   1.055355      2140.0  2.575211     35.13   
3148    2.3917      10.0  6.589686   1.356502      1167.0  2.616592     35.27   
14229   4.0668      14.0  4.719346   0.930518      2139.0  2.914169     32.67   
17950   5.3873      18.0  4.958659   1.049162      1901.0  2.124022     37.34   
6884    4.7222      20.0  5.164456   1.013263      3273.0  2.893899     34.04   
462     1.7464      35.0  3.218000   1.108000      1675.0  1.675000     37.87   
1341    4.6628      16.0  5.413721   0.943867      1696.0  3.525988     38.01   
18805   2.1513       8.0  8.117845   1.558923       786.0  2.646465     40.61   
19855   2.3365      22.0  6.468085   1.180851      1076.0  3.815603     36.35   
459     1.1696      52.0  2.436000   0.944000      1349.0  5.396000     37.87   
4895    2.3750      48.0  3.600000   0.900000       485.0  4.409091     34.01   
10986   3.4152      34.0  4.691358   1.059965      1475.0  2.601411     33.75   
9026    8.0144      16.0  8.191860   1.418605       970.0  5.639535     34.07   
12071   5.2898      25.0  6.722008   1.028958      3240.0  3.127413     33.86   
3318    2.5326      20.0  6.292490   1.

**3. Dimensionality reduction**

In [6]:
dr = PCA(n_components=2) # 2 dimensões PCA
dr.fit(dframe)
df_pca = dr.transform(dframe)
print(df_pca)

[[-1103.51264821     8.56663624]
 [  975.54124442    -4.67041774]
 [ -929.54990812    20.03465092]
 ...
 [ -418.43757543   -12.90825582]
 [ -684.43952537   -12.79458051]
 [  -38.43624736   -12.67037806]]


**4. Feature subset selection**


In [7]:
fss = dframe.loc[dframe["HouseAge"]<10,:]

fss.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
59   2.5625       2.0  2.771930   0.754386        94.0  1.649123     37.82   
570  7.6110       5.0  6.855776   1.061442      7427.0  2.732524     37.72   
577  7.0568       5.0  7.023438   0.912109      1738.0  3.394531     37.73   
631  3.6630       5.0  5.158537   1.213415       814.0  2.481707     37.72   
676  5.4858       5.0  5.204489   1.014963       840.0  2.094763     37.68   

     Longitude  
59     -122.29  
570    -122.24  
577    -122.06  
631    -122.17  
676    -122.18

**5. Feature Creation**

In [9]:
new_data = np.concatenate((data.data, data.target.reshape(-1,1)*100000), axis=1)
names = data.feature_names + ["Preços"]
dframe = pd.DataFrame(data=new_data, columns=names)
dframe

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
5      4.0368      52.0  4.761658   1.103627       413.0  2.139896     37.85   
6      3.6591      52.0  4.931907   0.951362      1094.0  2.128405     37.84   
7      3.1200      52.0  4.797527   1.061824      1157.0  1.788253     37.84   
8      2.0804      42.0  4.294118   1.117647      1206.0  2.026891     37.84   
9      3.6912      52.0  4.970588   0.990196      1551.0  2.172269     37.84   
10     3.2031      52.0  5.477612   1.079602       910.0  2.263682     37.85   
11     3.2705      52.0  4.772480   1.024523      1504.0  2.049046     37.85   
12     3.0750      52.0  5.322650   1.012821      1098.0  2.346154     37.85   
13     2.6736      52.0  4.000000   1.097701       345.0  1.982759     37.84   
14     1.9167      52.0  4.262903   1.009677      1212.0  1.954839     37.85   
15     2.1250      50.0  4.242424   1.071970       697.0  2.640152     37.85   
16     2.7750      52.0  5.939577   1.048338       793.0  2.395770     37.85   
17     2.1202      52.0  4.052805   0.966997       648.0  2.138614     37.85   
18     1.9911      50.0  5.343675   1.085919       990.0  2.362768     37.84   
19     2.6033      52.0  5.465455   1.083636       690.0  2.509091     37.84   
20     1.3578      40.0  4.524096   1.108434       409.0  2.463855     37.85   
21     1.7135      42.0  4.478142   1.002732       929.0  2.538251     37.85   
22     1.7250      52.0  5.096234   1.131799      1015.0  2.123431     37.84   
23     2.1806      52.0  5.193846   1.036923       853.0  2.624615     37.84   
24     2.6000      52.0  5.270142   1.035545      1006.0  2.383886     37.84   
25     2.4038      41.0  4.495798   1.033613       317.0  2.663866     37.85   
26     2.4597      49.0  4.728033   1.020921       607.0  2.539749     37.85   
27     1.8080      52.0  4.780856   1.060453      1102.0  2.775819     37.85   
28     1.6424      50.0  4.401691   1.040169      1131.0  2.391121     37.84   
29     1.6875      52.0  4.703226   1.032258       395.0  2.548387     37.84   
...       ...       ...       ...        ...         ...       ...       ...   
20610  1.3631      28.0  4.851936   1.102506      1195.0  2.722096     39.10   
20611  1.2857      27.0  4.359413   1.078240      1163.0  2.843521     39.10   
20612  1.4934      26.0  5.157303   1.082397       761.0  2.850187     39.08   
20613  1.4958      31.0  4.500000   0.950521      1167.0  3.039062     39.09   
20614  2.4695      26.0  4.801688   0.970464      1455.0  3.069620     39.08   
20615  2.3598      23.0  5.461929   1.096447       724.0  3.675127     39.08   
20616  2.0469      15.0  4.826667   1.176000      1157.0  3.085333     39.08   
20617  3.3021      20.0  4.921053   0.956140       308.0  2.701754     39.06   
20618  2.2500      25.0  5.893805   1.092920       726.0  3.212389     39.06   
20619  2.7303      22.0  6.388514   1.148649      1023.0  3.456081     39.01   
20620  4.5625      40.0  4.125000   0.854167       151.0  3.145833     39.05   
20621  2.3661      37.0  7.923567   1.573248       484.0  3.082803     39.01   
20622  2.4167      20.0  4.808917   0.936306       457.0  2.910828     39.00   
20623  2.8235      32.0  5.101322   1.074890       598.0  2.634361     39.03   
20624  3.0739      16.0  5.835052   1.030928       731.0  2.512027     39.04   
20625  4.1250      37.0  7.285714   1.214286        29.0  2.071429     39.12   
20626  2.1667      36.0  6.573099   1.076023       504.0  2.947368     39.18   
20627  3.0000       5.0  6.067797   1.101695       169.0  2.864407     39.13   
20628  

**6. Discretization Binarization**

In [10]:
discbi = preprocessing.Binarizer().fit(dframe)
print(discbi)
discbi.threshold=3.5
dframe
discbi.transform(dframe)[:10,:]

Binarizer(copy=True, threshold=0.0)


array([[1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.]])

**7. Feature Transformation**

In [12]:
def func(x):
    return [x[0],x.name**2,x.name*x[1]]
  
dframe[:3]

dframe.apply(func, axis=1)

0                     [8.3252, 0, 0.0]
1                    [8.3014, 1, 21.0]
2                   [7.2574, 4, 104.0]
3                   [5.6431, 9, 156.0]
4                  [3.8462, 16, 208.0]
5                  [4.0368, 25, 260.0]
6                  [3.6591, 36, 312.0]
7                    [3.12, 49, 364.0]
8                  [2.0804, 64, 336.0]
9                  [3.6912, 81, 468.0]
10                [3.2031, 100, 520.0]
11                [3.2705, 121, 572.0]
12                 [3.075, 144, 624.0]
13                [2.6736, 169, 676.0]
14                [1.9167, 196, 728.0]
15                 [2.125, 225, 750.0]
16                 [2.775, 256, 832.0]
17                [2.1202, 289, 884.0]
18                [1.9911, 324, 900.0]
19                [2.6033, 361, 988.0]
20                [1.3578, 400, 800.0]
21                [1.7135, 441, 882.0]
22                [1.725, 484, 1144.0]
23               [2.1806, 529, 1196.0]
24                  [2.6, 576, 1248.0]
25               [2.4038,

**8. Attribute Transformation**

In [13]:
import sklearn.datasets as datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from sklearn import preprocessing

#import data to variable
data = datasets.california_housing.fetch_california_housing()

#Feature creation
new_data =np.concatenate((data.data, data.target.reshape(-1,1)*100000), axis=1)
names = data.feature_names + ["Preços"]
dframe = pd.DataFrame(data=new_data, columns=names)
dframe

#Discretization Binarization
binarizer = preprocessing.Binarizer().fit(dframe)
print(binarizer)
binarizer.threshold=3.5
dframe
binarizer.transform(dframe)[:10,:]

Binarizer(copy=True, threshold=0.0)


array([[1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 0., 1.]])